name: lexivo_assistant_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  swipeable_button_view: ^0.0.2
  glassmorphism: ^2.0.0
  percent_indicator: ^4.2.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_analytics: ^12.0.0
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lexivo_bot.png
