name: lexivo_assistant_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  swipeable_button_view: ^0.0.2
  glassmorphism: ^2.0.0
  percent_indicator: ^4.2.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_analytics: ^12.0.0
  cloud_firestore: ^6.0.0
  fl_chart: ^0.60.0
  intl: ^0.18.1
  flutter_tts: ^4.2.3
  glass_kit: ^4.0.1
  all_english_words: ^1.0.3
  http: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lexivo_bot.png
    - assets/words.json

fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-Regular.ttf
        - asset: fonts/Lexend-Medium.ttf
          weight: 500
        - asset: fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: fonts/Lexend-Bold.ttf
          weight: 700
