// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5t0PxQGfMfJU2cccP5Lis2HHPgp_i_Q8',
    appId: '1:711526249389:android:0f6d0aab4189ee370ae724',
    messagingSenderId: '711526249389',
    projectId: 'lexivo---dyslexia-assistant',
    storageBucket: 'lexivo---dyslexia-assistant.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz4Ks3y_wb5JwzTbQ7KRO2CzoPShoe8L0',
    appId: '1:711526249389:web:f515c6152085cbc60ae724',
    messagingSenderId: '711526249389',
    projectId: 'lexivo---dyslexia-assistant',
    authDomain: 'lexivo---dyslexia-assistant.firebaseapp.com',
    storageBucket: 'lexivo---dyslexia-assistant.firebasestorage.app',
    measurementId: 'G-H7YXLTGXT8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9iNY61EZ91jg62LQaZDOh3lVgk2GGuoI',
    appId: '1:711526249389:ios:f59daae53390310a0ae724',
    messagingSenderId: '711526249389',
    projectId: 'lexivo---dyslexia-assistant',
    storageBucket: 'lexivo---dyslexia-assistant.firebasestorage.app',
    iosBundleId: 'com.example.lexivoAssistant1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9iNY61EZ91jg62LQaZDOh3lVgk2GGuoI',
    appId: '1:711526249389:ios:f59daae53390310a0ae724',
    messagingSenderId: '711526249389',
    projectId: 'lexivo---dyslexia-assistant',
    storageBucket: 'lexivo---dyslexia-assistant.firebasestorage.app',
    iosBundleId: 'com.example.lexivoAssistant1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz4Ks3y_wb5JwzTbQ7KRO2CzoPShoe8L0',
    appId: '1:711526249389:web:941c6134487911770ae724',
    messagingSenderId: '711526249389',
    projectId: 'lexivo---dyslexia-assistant',
    authDomain: 'lexivo---dyslexia-assistant.firebaseapp.com',
    storageBucket: 'lexivo---dyslexia-assistant.firebasestorage.app',
    measurementId: 'G-CPVDVWXRW3',
  );

}